blog/urls.py
from __future__ import unicode_literals
from django.conf.urls import include, url

from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'', include('lbe.urls', namespace='lbe')),
]

handler404 = 'lbe.views.e404'

lbe/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.conf.urls import url
from lbe.views import ArticleList, ArticleDetail, CategoryList, CommentAdd, \
    CommentReply, RSS, CategoryRSS, ArticleCommentsRSS

urlpatterns = [
    url(r'^$', ArticleList.as_view(), name='article_list'),
    url(r'^feed/$', RSS(), name='rss'),
    url(r'^category/(?P<slug>[-_\w]+)/$', CategoryList.as_view(), name='category'),
    url(r'^category/(?P<slug>[-_\w]+)/feed/$', CategoryRSS(), name='category_rss'),
    url(r'^comment/add/$', CommentAdd.as_view(), name='comment_add'),
    url(r'^comment/reply/(?P<article>\d+)/(?P<pk>\d+)$', CommentReply.as_view(), name='comment_reply'),
    url(r'^(?P<slug>[-_\w]+)/$', ArticleDetail.as_view(), name='article'),
    url(r'^(?P<slug>[-_\w]+)/comments/feed/$', ArticleCommentsRSS(), name='article_comments_rss'),
]

lbe/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
import re
import hashlib
import mistune
from pygments import highlight
from pygments.lexers import get_lexer_by_name
from pygments.formatters import HtmlFormatter
from django.db import models
from django.core.exceptions import PermissionDenied, ValidationError
from django.core.urlresolvers import reverse
from django.utils.encoding import python_2_unicode_compatible
from django.utils.html import strip_tags
from django.utils.safestring import mark_safe
from django.utils.translation import ugettext as _
from django.utils.six.moves.urllib.parse import urlparse
from django.utils import timezone


class PygmentsRenderer(mistune.Renderer):
    def block_code(self, code, lang=None):
        code = code.rstrip('\n')
        if not lang:
            code = mistune.escape(code, smart_amp=False)
            return '<pre><code>{0}\n</code></pre>\n'.format(code)
        lexer = get_lexer_by_name(lang, stripall=True)
        formatter = HtmlFormatter(cssclass='highlight ' + lang)
        return highlight(code, lexer, formatter)


@python_2_unicode_compatible
class TemplateSnippet(models.Model):
    name = models.CharField(_('snippet name'), unique=True, max_length=255)
    content = models.TextField(_('snippet content'))
    description = models.CharField(
        _('snippet description'), blank=True, max_length=255
    )

    class Meta():
        verbose_name = _('template snippet')
        verbose_name_plural = _('template snippets')

    def __str__(self):
        return '{}: {}'.format(self.name, self.description[:50])

    def clean(self):
        if re.compile('[^a-z_]').search(self.name) is not None:
            raise ValidationError(_('Invalid name (a-z and _ only)'))


@python_2_unicode_compatible
class Setting(models.Model):
    name = models.CharField(_('setting name'), unique=True, max_length=255)
    value = models.CharField(_('setting value'), blank=True, max_length=255)
    description = models.CharField(
        _('setting description'), blank=True, max_length=255
    )

    class Meta():
        verbose_name = _('setting')
        verbose_name_plural = _('settings')

    def __str__(self):
        return '{}: {}'.format(self.name, self.description[:50])

    def clean(self):
        if re.compile('[^a-z_]').search(self.name) is not None:
            raise ValidationError(_('Invalid name (a-z and _ only)'))


@python_2_unicode_compatible
class Category(models.Model):
    name = models.CharField(_('category name'), unique=True, max_length=255)
    slug = models.CharField(_('category slug'), unique=True, max_length=100)
    description = models.CharField(
        _('category description'), blank=True, max_length=255
    )

    class Meta():
        verbose_name = _('category')
        verbose_name_plural = _('categories')

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('lbe:category', args=[self.slug])


class ArticleQuerySet(models.QuerySet):
    def published_regular(self):
        return self.filter(is_published=True, is_standalone=False)

    def published_standalone(self):
        return self.filter(is_published=True, is_standalone=True)


@python_2_unicode_compatible
class Article(models.Model):
    title = models.CharField(_('article title'), max_length=255)
    content = models.TextField(_('article content'))
    created = models.DateTimeField(_('article created'))
    updated = models.DateTimeField(_('article updated'), auto_now=True)
    category = models.ForeignKey(
        Category, verbose_name=_('related category'), blank=True, null=True
    )
    slug = models.CharField(_('article slug'), unique=True, max_length=100)
    description = models.CharField(
        _('article description'), blank=True, max_length=255
    )
    is_comment_allowed = models.BooleanField(_('comment allowed'), default=True)
    is_standalone = models.BooleanField(_('standalone page'), default=False)
    is_published = models.BooleanField(_('article published'), default=False)

    objects = ArticleQuerySet.as_manager()

    class Meta():
        ordering = ['-created']
        verbose_name = _('article')
        verbose_name_plural = _('articles')

    def __str__(self):
        return self.title

    def get_content(self):
        return mark_safe(mistune.markdown(self.content,
                                          renderer=PygmentsRenderer()))

    def get_description(self):
        return self.description or (strip_tags(self.get_content())[:160]
                                    .replace('\n', ' ').replace('\r', ' '))

    def get_absolute_url(self):
        # this expression also used in Comment.get_absolute_url()
        return reverse('lbe:article', args=[self.slug])


@python_2_unicode_compatible
class SpamSnippet(models.Model):
    snippet = models.CharField(_('snippet'), unique=True, max_length=255)

    class Meta():
        verbose_name = _('spam snippet')
        verbose_name_plural = _('spam snippets')

    def __str__(self):
        return self.snippet[:30]


@python_2_unicode_compatible
class Comment(models.Model):
    article = models.ForeignKey(Article, verbose_name=_('related article'))
    parent = models.ForeignKey(
        'self', verbose_name=_('parent comment'), blank=True, null=True
    )
    user_name = models.CharField(_('name'), max_length=50)
    user_email = models.EmailField(_('email'), blank=True)
    user_url = models.URLField(_('website'), blank=True)
    content = models.TextField(_('comment'))
    created = models.DateTimeField(_('comment created'), blank=True, null=False)
    is_approved = models.BooleanField(_('comment approved'), default=False)

    class Meta():
        ordering = ['-created']
        verbose_name = _('comment')
        verbose_name_plural = _('comments')

    def __str__(self):
        content = strip_tags(self.get_content())
        return '{}: {}...'.format(self.user_name, content[:40].rstrip())

    def get_content(self):
        # don't use PygmentsRenderer here
        return mark_safe(mistune.markdown(self.content, escape=True))

    def get_user_avatar(self):
        return ''.join([
            "http://www.gravatar.com/avatar/",
            hashlib.md5(self.user_email.encode('utf-8')).hexdigest()
        ])

    def get_reply_link(self):
        return reverse('lbe:comment_reply', args=[self.article_id, self.id])

    _article_slug = None
    _article_url = None

    def get_absolute_url(self):
        # article slug can be fetched in same query with .extra()
        if self._article_slug is not None:
            self._article_url = reverse(
                'lbe:article', args=[self._article_slug]
            )
        if self._article_url is None:
            self._article_url = (
                Article.objects.only('slug').get(id=self.article_id)
                .get_absolute_url()
            )
        return '{}#comment-{}'.format(self._article_url, self.id)

    def clean(self):
        if not self.created:
            self.created = timezone.now()

        article = (
            Article.objects.only('is_comment_allowed')
            .filter(pk=self.article_id).first()
        )
        if not getattr(article, 'is_comment_allowed', False):
            raise PermissionDenied()

        spam = SpamSnippet.objects.values_list('snippet')
        fields = (self.user_name, self.user_email, self.user_url, self.content)
        for (snippet, ) in spam:
            if any(snippet.lower() in field.lower() for field in fields):
                raise PermissionDenied()

        if (self.user_name.startswith('http://') or
                self.user_name.endswith(('.com', '.org', '.net'))):
            raise ValidationError({
                'user_name': [_('Links are not allowed here'), ]
            })

        url = urlparse(self.user_url)
        if len(url.path) > 10 or len(url.query) > 10:
            raise ValidationError({
                'user_url': [_('This link is too long'), ]
            })

        if any(markup in self.content for markup in ('<a href', '[url')) or \
                self.content.startswith('http://'):
            raise ValidationError({
                'content': [_('Please, use Markdown syntax for links'), ]
            })

lbe/forms.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.forms import ModelForm, widgets as w
from django.utils.translation import ugettext as _
from pagedown.widgets import PagedownWidget
from lbe.models import Comment


class CommentForm(ModelForm):

    class Meta():
        model = Comment
        exclude = ['is_approved', 'created']
        widgets = {
            'article': w.HiddenInput, 'parent': w.HiddenInput,
            'content': PagedownWidget,
            'user_email': w.TextInput(attrs={'placeholder':
                                             _('for gravatar service only')})
        }

lbe/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.contrib.sites.models import Site
from django.views.generic import DetailView, ListView
from django.views.generic.edit import CreateView
from django.db.models import Count
from django.core.exceptions import ObjectDoesNotExist, PermissionDenied
from django.core.urlresolvers import reverse
from django.shortcuts import render, get_object_or_404
from django.utils.translation import ugettext as _
from django.utils.six.moves.urllib.parse import urlparse
from django.contrib.syndication.views import Feed
from lbe.models import Setting, Category, Article, Comment
from lbe.forms import CommentForm
from lbe.utils import make_tree


def add_user_session_data(instance, form_initial):
    request = instance.request
    if request.user.is_authenticated():
        data = {
            'user_name': request.user.username,
            'user_email': request.user.email,
            'user_url': '{}://{}'.format(request.scheme,
                                         Site.objects.get_current().domain)
        }
    else:
        data = request.session.get('user_data', {})
    form_initial.update(data)
    return form_initial


class ArticleDetail(DetailView):
    model = Article

    def get_queryset(self):
        qs = super(ArticleDetail, self).get_queryset()
        if not self.request.user.is_superuser:
            qs = qs.filter(is_published=True)
        return qs

    def get_context_data(self, **kwargs):
        ctx = super(ArticleDetail, self).get_context_data(**kwargs)
        comment_list = (
            Comment.objects.filter(article=self.object).order_by('created')
        )
        for comment in comment_list:
            comment._article_url = self.object.get_absolute_url()
            if not comment.is_approved:
                comment.url = ''
                comment.content = _('Comment is under moderation')
                comment.under_moderation_class = 'comment-under-moderation'
        ctx['comment_tree'] = make_tree(comment_list)
        ctx['comment_form'] = CommentForm(
            initial=add_user_session_data(self, {'article': self.object})
        )
        return ctx


class ArticleList(ListView):
    model = Article
    paginate_by = 10

    def get_queryset(self):
        qs = super(ArticleList, self).get_queryset()
        return qs.annotate(Count('comment')).filter(is_published=True,
                                                    is_standalone=False)


class CategoryList(ArticleList):
    def get_category(self):
        return get_object_or_404(Category, slug=self.kwargs['slug'])

    def get_queryset(self):
        qs = super(CategoryList, self).get_queryset()
        return qs.filter(category=self.get_category())

    def get_context_data(self, **kwargs):
        ctx = super(CategoryList, self).get_context_data(**kwargs)
        ctx['category'] = self.get_category()
        return ctx


class CommentAdd(CreateView):
    model = Comment
    form_class = CommentForm
    http_method_names = ['post']
    template_name = 'lbe/comment_add.html'

    def form_valid(self, form):
        if not self.request.user.is_authenticated():
            self.request.session['user_data'] = {
                field: form.cleaned_data[field]
                for field in ['user_name', 'user_email', 'user_url']
            }
        if self.request.user.is_superuser:
            form.instance.is_approved = True
        return super(CommentAdd, self).form_valid(form)


class CommentReply(CommentAdd):
    http_method_names = ['get', 'post']

    def get_initial(self):
        # GET method is allowed, so we need to have some antispam protection
        article = Article.objects.only('slug').get(id=self.kwargs['article'])
        referer = urlparse(self.request.META.get('HTTP_REFERER', ''))
        if article.slug not in referer.path:  # /slug/
            raise PermissionDenied()
        return add_user_session_data(self, {'article': self.kwargs['article'],
                                            'parent': self.kwargs['pk']})


class RSS(Feed):
    def title(self):
        try:
            return Setting.objects.get(name='site_title').value
        except ObjectDoesNotExist:
            return ''

    def description(self):
        try:
            return Setting.objects.get(name='site_description').value
        except ObjectDoesNotExist:
            return ''

    def link(self):
        return reverse('lbe:rss')

    def items(self):
        return Article.objects.published_regular()[:10]

    def item_title(self, item):
        return item.title

    def item_description(self, item):
        return item.get_content()

    def item_pubdate(self, item):
        return item.created


class CategoryRSS(RSS):
    def __call__(self, request, *args, **kwargs):
        self.category = get_object_or_404(Category, slug=kwargs['slug'])
        return super(CategoryRSS, self).__call__(request, *args, **kwargs)

    def title(self):
        try:
            title = Setting.objects.get(name='site_title').value
            return ''.join([title, ' » ', self.category.name])
        except ObjectDoesNotExist:
            return self.category.name

    def description(self):
        return self.category.description

    def link(self):
        return reverse('lbe:category_rss', args=[self.category.slug])

    def items(self):
        articles = Article.objects.published_regular()
        return articles.filter(category=self.category)[:10]


class ArticleCommentsRSS(Feed):
    def __call__(self, request, *args, **kwargs):
        self.article = get_object_or_404(
            Article, slug=kwargs['slug'], is_published=True
        )
        return super(ArticleCommentsRSS, self).__call__(request,
                                                        *args, **kwargs)

    def title(self):
        return ''.join([self.article.title, ' » ', _('comments')])

    def description(self):
        return _('Comments')

    def link(self):
        return reverse('lbe:article_comments_rss', args=[self.article.slug])

    def items(self):
        qs = Comment.objects.filter(is_approved=True, article=self.article)
        return qs[:25]

    def item_title(self, item):
        return item.user_name

    def item_description(self, item):
        return item.get_content()

    def item_pubdate(self, item):
        return item.created


def e404(request):
    return render(request, 'lbe/404.html', {}, status=404)

lbe/templates/lbe/article_detail.html
{% extends 'lbe/base.html' %}

{% load i18n %}
{% load staticfiles %}

{% block title %}
    {{ article.title }} - {{ site_title }}
{% endblock %}

{% block description %}
    <meta name="description" content="{{ article.get_description }}">
{% endblock %}

{% block form_css %}
    {{ comment_form.media.css }}
{% endblock %}

{% block form_js %}
    {{ comment_form.media.js }}
    <script src="{% static 'lbe/comment_reply.js' %}"></script>
{% endblock %}

{% block alternate %}
    <link rel="alternate" type="application/rss+xml" title="{{ site_title }} - {% trans 'comments' %}" href="{% url 'lbe:article_comments_rss' article.slug %}">
{% endblock %}

{% block content %}
<div class="article">
    <h1 class="article-title">{{ article.title }}</h1>
    {{ article.get_content }}
    <ul class="article-meta-list">
        {% if user.is_authenticated %}
            <li class="article-meta-edit">
                <a class="article-meta-edit-link" href="{% url 'admin:lbe_article_change' article.id %}">{% trans 'Edit' %}</a>
            </li>
        {% endif %}
        <li class="article-meta-published">
            {% trans 'Published' %}: {{ article.created|date:'d E Y' }}
        </li>
        <li class="article-meta-updated">
            {% trans 'Updated' %}: {{ article.updated|date:'d E Y' }}
        </li>
        {% if article.category %}
            <li class="article-meta-category">
                {% trans 'Category' %}:
                <a class="article-meta-category-link" href="{{ article.category.get_absolute_url }}">{{ article.category.name }}</a>
            </li>
        {% endif %}
    </ul>
</div>

{% if comment_tree %}
    <div id="comments" class="comment-tree">
        <h2 class="comment-tree-header">
            {% trans 'Comments' %}
            <span class="comment-tree-header-rss">
                (<a class="comment-tree-header-rss-link" rel="alternate" type="application/rss+xml" title="{{ site_title }} - {% trans 'comments' %}" href="{% url 'lbe:article_comments_rss' article.slug %}">RSS</a>)
            </span>
        </h2>
        <div class="comment-tree-container">
            {% with 'lbe/comment_tree.html' as comment_template %}
                {% include comment_template %}
            {% endwith %}
        </div>
    </div>
{% endif %}

{% if article.is_comment_allowed %}
    {% include 'lbe/comment_form.html' with form=comment_form %}
{% endif %}
{% endblock %}

lbe/templates/lbe/article_list.html
{% extends 'lbe/base.html' %}

{% load i18n %}

{% block title %}
    {% if category %}
        {{ category.name }} - {{ site_title }}
    {% else %}
        {{ site_title }}
    {% endif %}
{% endblock %}

{% block alternate %}
    {% if category %}
        <link rel="alternate" type="application/rss+xml" title="{{ site_title }} - {{ category.name }}" href="{% url 'lbe:category_rss' category.slug %}">
    {% endif %}
{% endblock %}

{% block content %}
    {% for article in article_list %}
    <div class="article">
        <h1 class="article-title">
            <a class="article-title-link" href="{{ article.get_absolute_url }}">{{ article.title }}</a>
        </h1>
        {% with article.get_content as content %}
            {{ content|truncatewords_html:60 }}
            {% if content|wordcount > 60 %}
                <div class="article-readmore">
                    <a class="article-readmore-link" href="{{ article.get_absolute_url }}" title="{{ article.title }}">Полная версия »</a>
                </div>
            {% endif %}
        {% endwith %}
        <ul class="article-meta-list">
            {% if user.is_authenticated %}
                <li class="article-meta-edit">
                    <a class="article-meta-edit-link" href="{% url 'admin:lbe_article_change' article.id %}">{% trans 'Edit' %}</a>
                </li>
            {% endif %}
            <li class="article-meta-comments">
                <a class="article-meta-comments-link" href="{{ article.get_absolute_url }}#comments">{% trans 'Comments' %}: {{ article.comment__count }}</a>
            </li>
            <li class="article-meta-updated">
                {% trans 'Updated' %}: {{ article.updated|date:'d E Y' }}
            </li>
        </ul>
    </div>
    {% endfor %}
    {% if is_paginated %}
    <ul class="content-pagination-list">
        {% if page_obj.has_previous %}
            <li class="content-pagination-item content-pagination-prev">
                <a class="content-pagination-link" href="?page={{ page_obj.previous_page_number }}">&laquo; {% trans 'Previous page' %}</a>
            </li>
        {% endif %}
        {% for page in paginator.page_range %}
            {% if page == page_obj.number %}
                <li class="content-pagination-item">
                    <span class="content-pagination-active">{{ page }}</span>
                </li>
            {% else %}
                <li class="content-pagination-item">
                    <a class="content-pagination-link" href="?page={{ page }}">{{ page }}</a>
                </li>
            {% endif %}
        {% endfor %}
        {% if page_obj.has_next %}
            <li class="content-pagination-item content-pagination-next">
                <a class="content-pagination-link" href="?page={{ page_obj.next_page_number }}">{% trans 'Next page' %} &raquo;</a>
            </li>
        {% endif %}
    </ul>
    {% endif %}
{% endblock %}

lbe/templates/lbe/base.html
<!DOCTYPE html>
<html lang="{{ LANGUAGE_CODE }}">
<head>
    {% load i18n %}
    {% load staticfiles %}
    <meta charset="utf-8">
    <title>{% block title %}{{ site_title }}{% endblock %}</title>
    {% block description %}
        <meta name="description" content="{{ site_description }}">
    {% endblock %}
    <link rel="stylesheet" href="{% static 'imagelightbox/imagelightbox-extended.min.css' %}">
    {% block form_css %}{% endblock %}
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link rel="alternate" type="application/rss+xml" title="{{ site_title }}" href="{% url 'lbe:rss' %}">
    {% block alternate %}{% endblock %}
</head>
<body>

<div class="site-header">
<div class="site-container">
    <h1 class="site-header-title">
        <a class="site-header-title-link" href="{% url 'lbe:article_list' %}">{{ site_title }}</a>
    </h1>
</div>
</div>

<div class="site-main">
<div class="site-container">
    <div class="site-content">
    {% block content %}
    {% endblock %}
    </div>

    <div class="site-sidebar">
        {% if aside_pages_list %}
            <div class="widget widget_aside widget-pages">
                <h1 class="widget-header">{% trans 'Pages' %}</h1>
                <ul class="widget-data-list">
                    {% for p in aside_pages_list %}
                        <li class="widget-data-item">
                            <a class="widget-data-link" href="{{ p.get_absolute_url }}">{{ p.title }}</a>
                        </li>
                    {% endfor %}
                </ul>
            </div>
        {% endif %}
        {% if aside_category_list %}
            <div class="widget widget_aside widget-categories">
                <h1 class="widget-header">{% trans 'Categories' %}</h1>
                <ul class="widget-data-list">
                    {% for cat in aside_category_list %}
                        <li class="widget-data-item">
                            <a class="widget-data-link" href="{{ cat.get_absolute_url }}" title="{{ cat.description }}">{{ cat.name }}</a>
                        </li>
                    {% endfor %}
                </ul>
            </div>
        {% endif %}
        {% if aside_comment_list %}
            <div class="widget widget_aside widget-latest-comments">
                <h1 class="widget-header">{% trans 'Latest comments' %}</h1>
                {% for c in aside_comment_list %}
                    <div class="comment comment-level-1">
                        <div class="comment-wrapper">
                            <div class="comment-header">
                                <img class="comment-header-avatar" src="{{ c.get_user_avatar }}?s=35&amp;d=mm" alt="">
                                <div class="comment-header-author">
                                    {% if c.user_url %}
                                        <a class="comment-header-author-link" href="{{ c.user_url }}">{{ c.user_name }}</a>:
                                    {% else %}
                                        <span class="comment-header-author-name">{{ c.user_name }}</span>:
                                    {% endif %}
                                </div>
                                <div class="comment-header-anchor">
                                    <a class="comment-header-anchor-link" href="{{ c.get_absolute_url }}">{{ c.created|date:'d E Y' }} {% trans 'at' %} {{ c.created|time:'H:i' }}</a>
                                </div>
                            </div>
                            <div class="comment-content comment-content_aside">
                                <a class="comment-data-link" href="{{ c.get_absolute_url }}">
                                <p>{{ c.get_content|striptags|truncatewords:20 }}</p>
                                </a>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        {% endif %}
    </div>
</div>
</div>

<div class="site-footer">
<div class="site-container">
    <div class="site-footer-copyright">{{ site_copyright }}</div>
</div>
</div>

<script src="{% static 'jquery-2.1.4.min.js' %}"></script>
<script src="{% static 'imagelightbox/imagelightbox.min.js' %}"></script>
<script src="{% static 'imagelightbox/imagelightbox-extended.min.js' %}"></script>
<script>$('a[rel^=lightbox], a[data-lightbox]').imageLightboxExtended({quitOnEnd: true})</script>
{% block form_js %}{% endblock %}

{{ site_counters }}

</body>
</html>

lbe/templates/lbe/comment_add.html
{% extends 'lbe/base.html' %}

{% block form_css %}
    {{ form.media.css }}
{% endblock %}

{% block form_js %}
    {{ form.media.js }}
{% endblock %}

{% block content %}
    {% include 'lbe/comment_form.html' %}
{% endblock %}

lbe/templates/lbe/comment_form.html
{% load i18n %}

<div class="comment-form-container">
    <form class="comment-form" method="post" action="{% url 'lbe:comment_add' %}">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="{% trans 'Submit' %}">
    </form>
</div>

lbe/templates/lbe/comment_tree.html
{% load i18n %}

{% for c in comment_tree %}
<div id="comment-{{ c.id }}" class="comment comment-level-{{ c.level }}">
    <div class="comment-wrapper {{ c.under_moderation_class }}">
        <div class="comment-header">
            <img class="comment-header-avatar" src="{{ c.get_user_avatar }}?s=35&amp;d=mm" alt="">
            <div class="comment-header-author">
                {% if c.user_url %}
                    <a class="comment-header-author-link" href="{{ c.user_url }}">{{ c.user_name }}</a>:
                {% else %}
                    <span class="comment-header-author-name">{{ c.user_name }}</span>:
                {% endif %}
            </div>
            <div class="comment-header-anchor">
                <a class="comment-header-anchor-link" href="{{ c.get_absolute_url }}">
                    {{ c.created|date:'d E Y' }} {% trans 'at' %} {{ c.created|time:'H:i' }}
                </a>
            </div>
        </div>
        <div class="comment-content">{{ c.get_content }}</div>
        {% if c.is_approved %}
            <a href="{{ c.get_reply_link }}" class="comment-reply-link" data-id="{{ c.id }}">{% trans 'Reply' %}</a>
            <a href="#" class="comment-reply-cancel-link">{% trans 'Cancel reply' %}</a>
        {% endif %}
        {% if user.is_authenticated %}
            <a class="comment-edit-link" href="{% url 'admin:lbe_comment_change' c.id %}">{% trans 'Edit' %}</a>
        {% endif %}
    </div>
    {% if c.children %}
        {% include comment_template with comment_tree=c.children %}
    {% endif %}
</div>
{% endfor %}